/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      "colors": {
        "outline-variant": "#d4c5ab",
        "on-error-container": "#93000a",
        "surface-container-high": "#ece7e4",
        "tertiary-fixed": "#ffdcc4",
        "on-secondary-fixed-variant": "#2e4d3e",
        "primary-fixed-dim": "#fabd00",
        "surface-bright": "#fef8f5",
        "inverse-surface": "#32302e",
        "on-primary-fixed-variant": "#5b4300",
        "on-background": "#1d1b1a",
        "surface-variant": "#e7e1df",
        "on-primary-container": "#6d5100",
        "inverse-on-surface": "#f5f0ed",
        "surface-container": "#f2edea",
        "outline": "#827660",
        "primary-container": "#ffc107",
        "secondary-fixed": "#c7ebd6",
        "on-error": "#ffffff",
        "on-tertiary-fixed": "#2f1400",
        "secondary": "#456554",
        "secondary-fixed-dim": "#accfba",
        "error": "#ba1a1a",
        "on-surface-variant": "#4f4632",
        "on-tertiary-container": "#834509",
        "primary": "#785900",
        "surface-container-highest": "#e7e1df",
        "on-surface": "#1d1b1a",
        "surface-dim": "#ded9d6",
        "on-primary-fixed": "#261a00",
        "on-primary": "#ffffff",
        "on-secondary-container": "#4b6b5a",
        "secondary-container": "#c7ebd6",
        "tertiary": "#8e4e14",
        "on-tertiary": "#ffffff",
        "inverse-primary": "#fabd00",
        "tertiary-container": "#ffbd8c",
        "on-secondary": "#ffffff",
        "surface-container-lowest": "#ffffff",
        "background": "#fef8f5",
        "on-secondary-fixed": "#012114",
        "tertiary-fixed-dim": "#ffb780",
        "surface": "#fef8f5",
        "on-tertiary-fixed-variant": "#6f3800",
        "surface-container-low": "#f8f2f0",
        "error-container": "#ffdad6",
        "primary-fixed": "#ffdf9e",
        "surface-tint": "#785900"
      },
      "borderRadius": {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      "spacing": {
        "md": "24px",
        "xl": "80px",
        "base": "8px",
        "sm": "12px",
        "margin-desktop": "64px",
        "margin-mobile": "20px",
        "gutter": "24px",
        "xs": "4px",
        "lg": "48px"
      },
      "fontFamily": {
        "label-md": ["Inter", "sans-serif"],
        "headline-lg": ["Montserrat", "sans-serif"],
        "headline-md": ["Montserrat", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "headline-xl": ["Montserrat", "sans-serif"],
        "headline-lg-mobile": ["Montserrat", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "label-sm": ["Inter", "sans-serif"]
      },
      "fontSize": {
        "label-md": ["14px", { "lineHeight": "20px", "letterSpacing": "0.01em", "fontWeight": "600" }],
        "headline-lg": ["32px", { "lineHeight": "40px", "fontWeight": "600" }],
        "headline-md": ["24px", { "lineHeight": "32px", "fontWeight": "600" }],
        "body-md": ["16px", { "lineHeight": "24px", "fontWeight": "400" }],
        "headline-xl": ["40px", { "lineHeight": "48px", "letterSpacing": "-0.02em", "fontWeight": "700" }],
        "headline-lg-mobile": ["28px", { "lineHeight": "34px", "fontWeight": "600" }],
        "body-lg": ["18px", { "lineHeight": "28px", "fontWeight": "400" }],
        "label-sm": ["12px", { "lineHeight": "16px", "fontWeight": "500" }]
      }
    }
  },
  plugins: [],
}
